CREATE DATABASE IF NOT EXISTS apptienganh CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE apptienganh;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL
);
